djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LeadListView, SignUpView

urlpatterns = [
    path('', LeadListView.as_view()),
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import delete, LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_index'),
    path('new', LeadCreateView.as_view(), name='lead_new'),
    path('<pk>', LeadDetailView.as_view(), name='lead_show'),
    path('<pk>/update', LeadUpdateView.as_view(), name='lead_update'),
    path('<pk>/delete', LeadDeleteView.as_view(), name='lead_delete')
]

leads/models.py
from django.db.models import Model, CharField, IntegerField, BooleanField, ImageField, FileField, ForeignKey, OneToOneField, CASCADE
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Lead(Model):
    first_name = CharField(max_length=20)
    last_name = CharField(max_length=20)
    age = IntegerField(default=0)
    agent = ForeignKey('Agent', on_delete=CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(Model):
    user = OneToOneField(User, on_delete=CASCADE)

    def __str__(self):
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent'
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}

leads/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import LeadModelForm
from .models import Lead, Agent
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')

class LeadListView(ListView):
    template_name = "leads/index.html"
    queryset = Lead.objects.all()
    context_object_name = "leads"


def index(request):
    leads = Lead.objects.all()
    ctx = {
        'leads': leads
    }
    return render(request, 'leads/index.html', context=ctx)


class LeadDetailView(DetailView):
    template_name = "leads/show.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"


def show(request, pk):
    lead = Lead.objects.get(id=pk)
    ctx = {
        'lead': lead
    }
    return render(request, 'leads/show.html', context=ctx)


class LeadCreateView(CreateView):
    template_name = "leads/new.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:list_index")


def new(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')

    ctx = {
        'form': form
    }
    return render(request, 'leads/new.html', context=ctx)


class LeadUpdateView(UpdateView):
    template_name = "leads/update.html"
    queryset = Lead.objects.all()
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead_index")


def update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    print(request.method)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        print(form)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect("/leads")
        else:
            return HttpResponse('Form is invalid')

    ctx = {
        'form': form,
        'lead': lead
    }
    return render(request, 'leads/update.html', context=ctx)


class LeadDeleteView(DeleteView):
    template_name = "leads/delete.html"
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse("leads:lead_index")


def delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

leads/templates/leads/delete.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'leads:lead_index' %}">Go back</a>
    <p>Are you sure you want to delete this post?</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

leads/templates/leads/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Lead List</h1>
    <a class="button" href="{% url 'leads:lead_new' %}">Create new lead</a>
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Age</th>
            <th>Location</th>
            <th>Phone</th>
        </thead>
        <tbody>
            {% for lead in leads %}
                <tr>
                    <td><a href="{% url 'leads:lead_show' lead.id %}">{{ lead.first_name }} {{ lead.last_name }}</a></td>
                    <td>{{ lead.age }}</td>
                    <td>Lorem</td>
                    <td>0123456789</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

leads/templates/leads/new.html
{% extends 'base.html' %}

{% block content %}
     <h1>New lead</h1>
        <form method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit'>Submit</button>
        </form>
{% endblock content %}

leads/templates/leads/show.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Detail of {{ lead.first_name }} {{ lead.last_name }}</h1>
    <p>{{ lead.first_name }} {{ lead.last_name }}</p>
    <div>
        <a href="{% url 'leads:lead_update' lead.id %}">Update</a>
        <a href="{% url 'leads:lead_delete' lead.id %}">Delete</a>
    </div>
{% endblock content %}

leads/templates/leads/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
    <head>
        <title>Django CRM</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
        <span class="title">Django CRM</span>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="/leads" class="navbar-item">
        Leads
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a href="/signup" class="button is-primary">
            <strong>Sign up</strong>
          </a>
            {% if request.user.is_authenticated %}
              <a href="/login" class="button is-light">
                Log in
              </a>
            {% else %}
                You are logged in:
                <a class="button is-light">
                    {{ request.user.username }}
                </a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

templates/second_page.html
<html>
    <head>
        <title>Second page</title>
    </head>
    <body>
        <h1>Second page</h1>
    </body>
</html>